import { useEffect, useState } from 'react'
import { Users, Phone, Plus, Camera, ShieldCheck } from 'lucide-react'
import TextInput from '../components/common/TextInput'
import PhoneInput from '../components/common/PhoneInput'
import TextArea from '../components/common/TextArea'
import SelectInput from '../components/common/SelectInput'
import Button from '../components/common/Button'
import ErrorMessage from '../components/common/ErrorMessage'
import AddHelpersSuccess from '../components/add-helper/AddHelpersSuccess'
import ContactPicker from '../components/add-helper/ContactPicker'
import { getCategories, getServiceTypes } from '../services/categoryService'
import { submitHelper } from '../services/submissionService'

const blank={name:'',mobile:'',whatsapp:'',categoryId:'',serviceTypeId:'',area:'',description:'',submittedName:''}
export default function AddHelperPage(){ const [categories,setCategories]=useState([]); const [types,setTypes]=useState([]); const [success,setSuccess]=useState(false); const [error,setError]=useState(''); const [form,setForm]=useState(blank); useEffect(()=>{getCategories().then(setCategories)},[]); useEffect(()=>{ if(form.categoryId) getServiceTypes(form.categoryId).then(setTypes); else setTypes([])},[form.categoryId]); const submit=async(e)=>{e.preventDefault();setError('');setSuccess(false);try{await submitHelper(form);setSuccess(true);setForm(blank)}catch(err){setError(err.message)}}; const picked=(contacts)=>{const c=contacts?.[0]; if(c) setForm(f=>({...f,name:c.name?.[0]||'',mobile:c.tel?.[0]||''}))}; return <div className="px-4 py-5">
  <h1 className="text-[22px] font-black text-[#19212d]">Add Helpers</h1><p className="mt-1 text-xs leading-5 text-[#69717b]">Select contacts from your phone and share their details to help the community.</p>
  <div className="mt-4 rounded-[16px] border border-[#d9ebdc] bg-[#eef9f0] p-3 text-[11px] leading-5 text-[#4d6253]"><div className="flex gap-2"><ShieldCheck size={18} className="mt-0.5 shrink-0 text-[#159447]"/><span>We only read contacts you select. Nothing is saved without your approval.</span></div></div>
  <div className="mt-4"><ContactPicker onPick={picked}/></div>
  <div className="my-4 flex items-center gap-3 text-[10px] text-[#9a9da1]"><span className="h-px flex-1 bg-[#e5e1db]"/>OR<span className="h-px flex-1 bg-[#e5e1db]"/></div>
  {success && <div className="mb-4"><AddHelpersSuccess/></div>}
  <div className="mb-4 flex items-center gap-3 rounded-[16px] bg-[#fff4e2] p-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-white text-[#e28419]"><Users size={20}/></span><div><b className="text-[12px] text-[#333943]">Help our community grow</b><p className="mt-0.5 text-[10px] leading-4 text-[#777d84]">Add a trusted service provider so others can benefit.</p></div></div>
  <form onSubmit={submit} className="space-y-3 rounded-[18px] border border-[#ece7df] bg-white p-4 shadow-sm"><TextInput label="Name *" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><PhoneInput label="Mobile Number *" value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})} required/><PhoneInput label="WhatsApp Number" value={form.whatsapp} onChange={e=>setForm({...form,whatsapp:e.target.value})}/><SelectInput label="Category *" value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value,serviceTypeId:''})} required><option value="">Select category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name_en}</option>)}</SelectInput><SelectInput label="Service Type *" value={form.serviceTypeId} onChange={e=>setForm({...form,serviceTypeId:e.target.value})} required><option value="">Select service type</option>{types.map(t=><option key={t.id} value={t.id}>{t.name_en}</option>)}</SelectInput><TextInput label="Area *" value={form.area} onChange={e=>setForm({...form,area:e.target.value})} placeholder="e.g. Zadeshwar" required/><TextArea label="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} rows={3} placeholder="Short description (optional)"/><div className="flex h-20 items-center justify-center rounded-xl border border-dashed border-[#ccd5dd] bg-[#fafbfc] text-center text-[#4f91c7]"><div><Camera size={22} className="mx-auto"/><div className="mt-1 text-[10px] font-semibold">Photo upload coming next</div></div></div><TextInput label="Your Name (optional)" value={form.submittedName} onChange={e=>setForm({...form,submittedName:e.target.value})}/><ErrorMessage message={error}/><Button type="submit" className="w-full">Submit Helper</Button></form>
</div> }
